<?php
/**
 * @package Blox Page Builder
 * @author UniteCMS.net
 * @copyright (C) 2017 Unite CMS, All Rights Reserved. 
 * @license GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 * */
defined('BLOXBUILDER_INC') or die('Restricted access');

GlobalsUC::$arrServerSideText = array(
		"uncategorized"=>__("Uncategorized", BLOXBUILDER_TEXTDOMAIN),
		"all_addons"=>__("All Items", BLOXBUILDER_TEXTDOMAIN),
		"new_layout"=>__("New Layout", BLOXBUILDER_TEXTDOMAIN),
		"import_layout"=>__("Import Layout", BLOXBUILDER_TEXTDOMAIN),
		"import_layouts"=>__("Import Layouts", BLOXBUILDER_TEXTDOMAIN),
		"layouts_global_settings"=>__("Layouts Global Settings", BLOXBUILDER_TEXTDOMAIN),
		"save_layout_settings"=>__("Save Layout Settings", BLOXBUILDER_TEXTDOMAIN),
		"no_layouts_found"=>__("No Layouts Found", BLOXBUILDER_TEXTDOMAIN),
		"layout_title"=>__("Layout Title", BLOXBUILDER_TEXTDOMAIN),
		"edit_layout"=>__("Edit Layout", BLOXBUILDER_TEXTDOMAIN),
		"back_to_layouts_list"=>__("Back to layouts list", BLOXBUILDER_TEXTDOMAIN),
		"my_layouts"=>__("My Layouts", BLOXBUILDER_TEXTDOMAIN),
		"layout_deleted"=>__("Layout Deleted", BLOXBUILDER_TEXTDOMAIN),
		"layout_duplicated"=>__("Layout Duplicated", BLOXBUILDER_TEXTDOMAIN),
		"all_layouts"=>__("All Layouts", BLOXBUILDER_TEXTDOMAIN),
		"layouts_added_successfully"=>__("Layouts Added Successfully", BLOXBUILDER_TEXTDOMAIN),
		"uploading_layouts_file"=>__("Uploading Layouts file...", BLOXBUILDER_TEXTDOMAIN),
		"layout_created"=>__("Layout Created", BLOXBUILDER_TEXTDOMAIN),
		"layout_updated"=>__("Layout Updated", BLOXBUILDER_TEXTDOMAIN),
		"layout_imported"=>__("Layout Imported", BLOXBUILDER_TEXTDOMAIN),
		"layout_saved"=>__("Layout Saved", BLOXBUILDER_TEXTDOMAIN),
		"preview_layout"=>__("Preview Layout", BLOXBUILDER_TEXTDOMAIN),
		"manage_layout_categories"=>__("Manage Layout Categories", BLOXBUILDER_TEXTDOMAIN),
		"set_category_to_layout"=>__("Set Category To Layout", BLOXBUILDER_TEXTDOMAIN),
		"select_layouts_export_file"=>__("Select layouts export file", BLOXBUILDER_TEXTDOMAIN),
		"are_you_sure_to_delete_this_layout"=>__("Are you sure to delete this layout?", BLOXBUILDER_TEXTDOMAIN),
		"addon_library"=>__("Addon Library", BLOXBUILDER_TEXTDOMAIN),
		"search_layout"=>__("Search Layout", BLOXBUILDER_TEXTDOMAIN),
);


GlobalsUC::$arrClientSideText = array(
		"empty"=>__("Empty", BLOXBUILDER_TEXTDOMAIN),
		"new"=>__("New", BLOXBUILDER_TEXTDOMAIN),
		"add_item"=>__("Add Item",BLOXBUILDER_TEXTDOMAIN),
		"update_item"=>__("Update Item",BLOXBUILDER_TEXTDOMAIN),
		"edit_item"=>__("Edit Item",BLOXBUILDER_TEXTDOMAIN),
		"close"=>__("Close",BLOXBUILDER_TEXTDOMAIN),
		"cancel"=>__("Cancel",BLOXBUILDER_TEXTDOMAIN),
		"update"=>__("Update",BLOXBUILDER_TEXTDOMAIN),
		"restore"=>__("Restore",BLOXBUILDER_TEXTDOMAIN),
		"updating"=>__("Updating...",BLOXBUILDER_TEXTDOMAIN),
		"restoring"=>__("Restoring...",BLOXBUILDER_TEXTDOMAIN),
		"import"=>__("Import",BLOXBUILDER_TEXTDOMAIN),
		"edit"=>__("Edit",BLOXBUILDER_TEXTDOMAIN),
		"edit_addon"=>__("Edit Addon",BLOXBUILDER_TEXTDOMAIN),
		"addon_container_settings"=>__("Addon Container Settings",BLOXBUILDER_TEXTDOMAIN),
		"delete_addon"=>__("Delete Addon",BLOXBUILDER_TEXTDOMAIN),
		"duplicate_addon"=>__("Duplicate Addon",BLOXBUILDER_TEXTDOMAIN),
		"updating_categories_order"=>__("Updating Categories Order...",BLOXBUILDER_TEXTDOMAIN),		
		"set_addon"=>__("Set Addon",BLOXBUILDER_TEXTDOMAIN),
		"add_addon_to_column"=>__("Add Addon To Column",BLOXBUILDER_TEXTDOMAIN),
		"removing_addons"=>__("Removing...",BLOXBUILDER_TEXTDOMAIN),
		"updating_addon_title"=>__("Updating Title...",BLOXBUILDER_TEXTDOMAIN),
		"duplicating_addons"=>__("Duplicating...",BLOXBUILDER_TEXTDOMAIN),
		"updating_addons_order"=>__("Updating Order...",BLOXBUILDER_TEXTDOMAIN),
		"updating_addons"=>__("Updating...",BLOXBUILDER_TEXTDOMAIN),
		"copying_addons"=>__("Copying...",BLOXBUILDER_TEXTDOMAIN),
		"moving_addons"=>__("Moving...",BLOXBUILDER_TEXTDOMAIN),
		"confirm_remove_addons"=>__("Are you sure you want to delete these addons?",BLOXBUILDER_TEXTDOMAIN),
		"uc_textfield"=>__("Text Field",BLOXBUILDER_TEXTDOMAIN),
		"uc_textarea"=>__("Text Area",BLOXBUILDER_TEXTDOMAIN),
		"uc_checkbox"=>__("Checkbox",BLOXBUILDER_TEXTDOMAIN),
		"uc_dropdown"=>__("Dropdown",BLOXBUILDER_TEXTDOMAIN),
		"uc_radioboolean"=>__("Radio Boolean",BLOXBUILDER_TEXTDOMAIN),
		"uc_number"=>__("Number",BLOXBUILDER_TEXTDOMAIN),
		"uc_colorpicker"=>__("Color Picker",BLOXBUILDER_TEXTDOMAIN),
		"uc_editor"=>__("Editor",BLOXBUILDER_TEXTDOMAIN),
		"uc_icon"=>__("Icon Picker",BLOXBUILDER_TEXTDOMAIN),
		"uc_shape"=>__("Shape Picker",BLOXBUILDER_TEXTDOMAIN),
		"uc_addonpicker"=>__("Addon Picker",BLOXBUILDER_TEXTDOMAIN),
		"uc_map"=>__("Google Map Picker",BLOXBUILDER_TEXTDOMAIN),
		"uc_image"=>__("Image",BLOXBUILDER_TEXTDOMAIN),
		"uc_mp3"=>__("Audio",BLOXBUILDER_TEXTDOMAIN),
		"uc_post"=>__("Post",BLOXBUILDER_TEXTDOMAIN),
		"uc_posts_list"=>__("Posts List",BLOXBUILDER_TEXTDOMAIN),
		"uc_font_override"=>__("Font Override",BLOXBUILDER_TEXTDOMAIN),
		"uc_imagebase"=>__("Image Fields",BLOXBUILDER_TEXTDOMAIN),
		"uc_menu"=>__("Menu",BLOXBUILDER_TEXTDOMAIN),
		"choose_image"=>__("Choose Image",BLOXBUILDER_TEXTDOMAIN),
		"choose_audio"=>__("Choose Audio",BLOXBUILDER_TEXTDOMAIN),
		"edit_file"=>__("Edit File",BLOXBUILDER_TEXTDOMAIN),
		"save"=>__("Save",BLOXBUILDER_TEXTDOMAIN),
		"delete_op"=>__("Delete",BLOXBUILDER_TEXTDOMAIN),
		"duplicate_op"=>__("Duplicate",BLOXBUILDER_TEXTDOMAIN),
		"bulk"=>__("Bulk",BLOXBUILDER_TEXTDOMAIN),
		"delete_include"=>__("Delete Include",BLOXBUILDER_TEXTDOMAIN),
		"add_include"=>__("Add Include",BLOXBUILDER_TEXTDOMAIN),
		"include_settings"=>__("Include Settings",BLOXBUILDER_TEXTDOMAIN),
		"always"=>__("Always",BLOXBUILDER_TEXTDOMAIN),
		"never_include"=>__("Never Include",BLOXBUILDER_TEXTDOMAIN),
		"not_selected"=>__("Not Selected",BLOXBUILDER_TEXTDOMAIN),
		"choose_addon"=>__("Choose Addon",BLOXBUILDER_TEXTDOMAIN),
		
		"delete_row"=>__("Delete Row",BLOXBUILDER_TEXTDOMAIN),
		"duplicate_row"=>__("Duplicate Row",BLOXBUILDER_TEXTDOMAIN),
		"copy_row"=>__("Copy Row",BLOXBUILDER_TEXTDOMAIN),
		"delete_section"=>__("Delete Section",BLOXBUILDER_TEXTDOMAIN),
		"duplicate_section"=>__("Duplicate Section",BLOXBUILDER_TEXTDOMAIN),
		"copy_section"=>__("Copy Section",BLOXBUILDER_TEXTDOMAIN),
		"paste_section"=>__("Paste Section",BLOXBUILDER_TEXTDOMAIN),
		"save_to_library"=>__("Save To Library",BLOXBUILDER_TEXTDOMAIN),
		"in_buffer"=>__("In Buffer",BLOXBUILDER_TEXTDOMAIN),
		"delete_column"=>__("Delete Column",BLOXBUILDER_TEXTDOMAIN),
		"duplicate_column"=>__("Duplicate Column",BLOXBUILDER_TEXTDOMAIN),
		"column_settings"=>__("Column Settings",BLOXBUILDER_TEXTDOMAIN),
		"add_column"=>__("Add Column",BLOXBUILDER_TEXTDOMAIN),
		"move_row"=>__("Move Row",BLOXBUILDER_TEXTDOMAIN),
		"move_section"=>__("Move Section",BLOXBUILDER_TEXTDOMAIN),
		"move_column"=>__("Move Column",BLOXBUILDER_TEXTDOMAIN),
		"move_addon"=>__("Move Addon",BLOXBUILDER_TEXTDOMAIN),
		"settings"=>__("Settings",BLOXBUILDER_TEXTDOMAIN),
		"row"=>__("Row",BLOXBUILDER_TEXTDOMAIN),
		"section"=>__("Section",BLOXBUILDER_TEXTDOMAIN),
		"row_layout"=>__("Row Layout", BLOXBUILDER_TEXTDOMAIN),
		"more_actions"=>__("More Actions", BLOXBUILDER_TEXTDOMAIN),
		"less_actions"=>__("Less Actions", BLOXBUILDER_TEXTDOMAIN),
		"hidden_row"=>__("Hidden Row", BLOXBUILDER_TEXTDOMAIN),
		"hidden_column"=>__("Hidden Column", BLOXBUILDER_TEXTDOMAIN),
		"hidden_addon"=>__("Hidden Addon", BLOXBUILDER_TEXTDOMAIN),
		"section_anchor"=>__("Section Anchor", BLOXBUILDER_TEXTDOMAIN),
);

$filepathProviderClientText = GlobalsUC::$pathProvider."provider_client_text.php";

if(file_exists($filepathProviderClientText))
	require $filepathProviderClientText;
